---
title: "About Me"
date: "`r Sys.Date()`"
bibliography: my-pubs.bib
nocite: |
  @Costello2012a
  @Dowling2016
  @Rahimi2016
  @Szuwalski2016b
  @Fogarty2016
  @Ovando2016a
  @Costello2016
  @Hilborn2014b
  @Rosenberg2014
  @Ovando2016
  @Ovando2013
toc: false
linkcolor: blue
---

# [Click to View my CV](https://raw.githubusercontent.com/DanOvando/weird-fishes/master/static/about/ovando_cv_oct_2020.pdf)

# About This Blog

They say if you have to repeat the same task more than a three times write a function, and if you have explain the same material more than three times write a blog. In that spirit, most of these posts are my solutions to problems that I've frequently had to explain to myself or others, mostly in the form of longer vignettes. These aren't intended to be definitive "answers" to a problem, but rather illustrations of the approach that I chose to take. Hopefully these examples help you with your research, or at least spark conversations about better approaches. 


My work is mostly in fisheries, so many of the posts will be demonstrations of data-science tools that I've had to use to solve fisheries-related problems. Others will be discussions of papers and ideas in fisheries and natural resource management, and when time allows I'm hoping to squeeze in some general music-related data-science geekery. 


# Research

I develop data-driven tools and ideas to help manage marine resources. My current projects include using the behavior of fishermen to predict the abundance of fish, estimating the conservation impacts of marine protected areas, and integrating economic information into data-limited stock assessments. Other projects include helping design and teach fisheries management strategies, looking at the factors that help make fisheries management work, and researching the state of global marine resources.  

I received my B.S. from the University of Miami, and my Master's in Environmental Science and Management from the Bren School at UC Santa Barbara. After that I worked as a research scientist for the [Sustainable Fisheries Group](http://sfg.msi.ucsb.edu/) for several years, before returning to the Bren School to do a PhD with Dr. Chris Costello and Dr. Steve Gaines. I am currently a postdoctoral researcher with Dr. Ray Hilborn at the University of Washington School of Aquatic and Fishery Sciences.


# Selected Publications





